kind: pipeline
type: docker
name: default

steps:
  - name: Build
    image: node:20
    commands:
      - npm ci
      - npm run build
      - npm run build:server
      - mkdir -p deploy
      - cp -rv .next deploy/
      - cp -rv public deploy/
      - cp -rv dist deploy/
      - cp package.json deploy/
      - cp package-lock.json deploy/
      - cp next.config.ts deploy/
      - cd deploy && npm ci --omit=dev

  - name: Deploy
    image: docker:27-cli
    commands:
      - docker ps
      - docker volume create duemmer_geht_immer
      - docker run --rm -v duemmer_geht_immer:/target alpine sh -c "rm -rf /target/*"
      - tar -C deploy -cf - . | docker run --rm -i -v duemmer_geht_immer:/target alpine sh -c "tar -C /target -xf -"
      - docker stop duemmer_geht_immer || true
      - docker rm duemmer_geht_immer || true
      - |
        docker run -d \
          --name duemmer_geht_immer \
          --restart always \
          -p 780:3000 \
          -p 7553:3000 \
          -e NODE_ENV=production \
          -v duemmer_geht_immer:/app \
          -w /app \
          node:20-alpine node dist/server.js
